Lend_CRUD/Models/ErrorViewModel.cs
using System;

namespace Lend_CRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lend_CRUD/Models/Expense.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lend_CRUD.Models
{
    public class Expense
    {
        [Key]
        public int Id { get; set; }
        public string ExpenseName { get; set; }
        [Required]
        [Range(1,int.MaxValue,ErrorMessage ="Amount must be greater than 0!")]
        public int Amount { get; set; }
    }
}

Lend_CRUD/Models/item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace Lend_CRUD.Models
{
    public class item
    {
        [Key]
        public int id { get; set; }
        public string lender { get; set; }
        public string borrower { get; set; }
        public string itemName { get; set; }
    }
}

Lend_CRUD/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lend_CRUD.Data;
using Lend_CRUD.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lend_CRUD.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ExpenseController(ApplicationDbContext db) {
            _db = db;
        }
        public IActionResult Index() {
             IEnumerable<Expense> objList = _db.Expenses;
            return View(objList);

        }
        public IActionResult Create() {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Expense obj) {
            if (ModelState.IsValid) {
            _db.Expenses.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
            }
            return View(obj);
        }
        // GET Delete
        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Expenses.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Expenses.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Expenses.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        // GET Update
        public IActionResult Update(int? id)
        {
          
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Expenses.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST UPDATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Expense obj)
        {
            if (ModelState.IsValid)
            {
                _db.Expenses.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }
    }
}

Lend_CRUD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lend_CRUD.Models;

namespace Lend_CRUD.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lend_CRUD/Controllers/appointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Lend_CRUD.Controllers
{
    public class appointmentController : Controller
    {
        public IActionResult Index()
        {
            string todaysDate = DateTime.Now.ToShortDateString();
            return View();
        }
    }
}

Lend_CRUD/Controllers/itemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lend_CRUD.Data;
using Lend_CRUD.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lend_CRUD.Controllers
{
    public class itemController : Controller
    {
        private readonly ApplicationDbContext _db;
        public itemController(ApplicationDbContext db) {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<item> objList = _db.items;
            return View(objList);
        }
        

        public IActionResult Create()
        {
             
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(item obj) {
             _db.items.Add(obj);
             _db.SaveChanges();
          return RedirectToAction("Index");
        }

    }
}

Lend_CRUD/Views/Expense/Create.cshtml
@model Lend_CRUD.Models.Expense

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Expense</h2>
        </div>
                <div class="form-group row">
                        <label asp-for="ExpenseName"></label>
                        <input asp-for="ExpenseName" class="form-control" />                   
                </div>
                <div class="form-group row">
                        <label asp-for="Amount"></label>
                        <input asp-for="Amount" class="form-control" /> 
                        <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
              
                <div class="form-group row">
                            <input type="submit" class="btn btn-info " value="create" />
                            <a asp-action="Index" class="btn btn-danger">Back</a>
                </div>

            </div>
</form>

Lend_CRUD/Views/Expense/Delete.cshtml
@model Lend_CRUD.Models.Expense

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="ExpenseName"></label>
                    </div> 
                    <div class="col-6">
                        <input asp-for="ExpenseName" disabled class="form-control" />
                    </div>
                   

                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Amount"></label>
                    </div>
                    <div class="col-6">
                        <input asp-for="Amount" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                            <input type="submit" class="btn btn-danger w-75" value="Delete" />
                            <a asp-action="Index" class="btn btn-success w-75">Back</a>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Lend_CRUD/Views/Expense/Index.cshtml
@model IEnumerable<Lend_CRUD.Models.Expense>
<div class="container p-3">
    <div class="row pt-4">
    <div class="col-6">
    <h2 class="text-primary">Expenses List</h2>
    </div>
    <div class="col-6 text-right">
        <a asp-controller="Expense" asp-action="Create" class="btn btn-primary">
            Create New Expense
        </a>
    </div>
    </div>
    <br />

@if (Model.Count() > 0)
{
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Expense</th>
            <th>Amount</th>
            <th>Changes</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var expense in Model)
        {
            <tr>
                <td width="30%">@expense.ExpenseName</td>
                <td width="30%">@expense.Amount</td>
                <td width="40%">
                    <div class="col-6 text-right">
                        <a asp-controller="Expense" asp-action="Update" asp-route-Id="@expense.Id" class="btn btn-primary">Update </a>
                        <a asp-controller="Expense" asp-action="Delete" asp-route-Id="@expense.Id" class="btn btn-danger">Delete</a>
                    </div>

                </td>
            </tr>
        }
    </tbody>
</table> 
}
else {
<p>No Items Created Yet</p>
}
</div>

Lend_CRUD/Views/Expense/Update.cshtml
@model Lend_CRUD.Models.Expense

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ExpenseName"></label>
                    </div> 
                    <div class="col-4">
                        <input asp-for="ExpenseName" class="form-control" />
                        <span asp-validation-for="ExpenseName" class="text-danger"></span>
                    </div>
                   

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                    <div class="col-4">
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>


                </div>
                <div class="form-group row">
                            <input type="submit" class="btn btn-info w-75" value="Update" />
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Lend_CRUD/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Lend_CRUD/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lend_CRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Lend_CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lend_CRUD</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Lend_CRUD</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="item" asp-action="Index">My Borrowed Items</a></li>
                    <li><a asp-area="" asp-controller="Expense" asp-action="Index">My Expenses</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - Lend_CRUD</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Lend_CRUD/Views/appointment/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

Lend_CRUD/Views/item/Create.cshtml
@model Lend_CRUD.Models.item

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Item</h2>
        </div>
                <div class="form-group row">
                        <label asp-for="itemName"></label>
                        <input asp-for="itemName" class="form-control" />                   
                </div>
                <div class="form-group row">
                        <label asp-for="borrower"></label>
                        <input asp-for="borrower" class="form-control" />                    
                </div>
                <div class="form-group row">
                        <label asp-for="lender"></label>
                        <input asp-for="lender" class="form-control" />
                </div>
                <div class="form-group row">
                            <input type="submit" class="btn btn-info " value="create" />
                            <a asp-action="Index" class="btn btn-danger">Back</a>
                </div>

            </div>
</form>

Lend_CRUD/Views/item/Index.cshtml
@model IEnumerable<Lend_CRUD.Models.item>
<div class="container p-3">
    <div class="row pt-4">
    <div class="col-6">
    <h2 class="text-primary">Borrowed Items List</h2>
    </div>
    <div class="col-6 text-right">
        <a asp-controller="item" asp-action="Create" class="btn btn-primary">
            Create New Item
        </a>
    </div>
    </div>
    <br />

@if (Model.Count() > 0)
{
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Item Name</th>
            <th>Borrower</th>
            <th>Lender</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width="30%">@item.itemName</td>
                <td width="30%">@item.borrower</td>
                <td width="30%">@item.lender</td>
            </tr>
        }
    </tbody>
</table> 
}
else {
<p>No Items Created Yet</p>
}
</div>